### ISSUE TITLE
Error en el apartado de volver atras en el commit

### ISSUE THREAD

**Issue by ElAdrixHD** [KamiKeys/guia-git-basica#11]
Según tu documentación usas "... HEAD@{1}" para volver atras en el commit y no me funciona.

En vez de eso, me ha funcionado usar "... HEAD~1"

**Comment by KamiKeys** [comment]
Puede que hayas cometido algún error al escribirlo. He probado lo que dices y el error se produce cuando intento tu propuesta, en cambio sí que funciona lo que ya está en la documentación.

Un saludo.
